<img src="https://filoger.com/wp-content/uploads/2021/09/circle-logo-1536x1536.png" alt="Filoger" width="300" height="300">

<h1 align="center"><font size = 14>Hands-On Machine Learning</font></h1>
<h4 align="center">November, 2022<h4>
<h3 align="center"><font size = 7>Naive Bayes</font></h3>
<h3 align="center">Zahra Amini / Marziyeh Taheri</h3>
<br>
<br>
<br>
<br>
<br>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn import preprocessing

In [3]:
df = pd.read_csv('data1.txt')

In [4]:
df

  Gender  Height  Weight  Foot size
0      M    6.00     180         12
1      M    5.90     190         11
2      M    5.58     170         12
3      M    5.92     165         10
4      F    5.00     100          6
5      F    5.50     150          8
6      F    5.42     130          7
7      F    5.75     150          9

In [5]:
df.columns

Index(['Gender', 'Height', 'Weight', 'Foot size'], dtype='object')

In [7]:
df['Gender'].unique()

array(['M', 'F'], dtype=object)

# preprocessing

In [8]:
label_encoder = preprocessing.LabelEncoder()

In [9]:
df['Gender'] = label_encoder.fit_transform(df['Gender'])

In [10]:
df

   Gender  Height  Weight  Foot size
0       1    6.00     180         12
1       1    5.90     190         11
2       1    5.58     170         12
3       1    5.92     165         10
4       0    5.00     100          6
5       0    5.50     150          8
6       0    5.42     130          7
7       0    5.75     150          9

# X, y

In [11]:
C1 = df[df['Gender']==1]

C2 = df[df['Gender']==0]

In [12]:
X1 = C1.drop('Gender', axis=1)

X2 = C2.drop('Gender', axis=1)

In [13]:
y1 = C1['Gender']

y2 = C2['Gender']

# Naive Bayes

In [14]:
def parameters(X):
    mu=0
    t1=0
    t2=0
    sigma=0
    
    m = X.shape[0]
    mu = (1/m) * X.sum()
    
    t1 = ((X-mu)**2).sum()
    
    t2 = ((X-mu).sum())**2
    
    sigma = (t1 - (t2/m)) / (m-1)
    
    return mu, sigma

In [15]:
parameters(X1)

(Height         5.85
 Weight       176.25
 Foot size     11.25
 dtype: float64,
 Height         0.034267
 Weight       122.916667
 Foot size      0.916667
 dtype: float64)

In [17]:
def liklihood(x, c):
    mu, sigma = parameters(c)
    t1=0
    t2=0
    
    t1 = 1/(np.sqrt(2*np.pi*(sigma)))
    
    t2 = np.exp(-((x-mu)**2)/(2*sigma))
    
    L = np.array(t1) * np.array(t2)
    
    return L

In [18]:
def prior(df, yc):
    m = df.shape[0]
    prior = yc.shape[0]/m
    
    return prior

In [19]:
x_new = [6, 130, 8]

In [22]:
def make_d(df, y1, y2, x_new, X1, X2):
    
    p1= prior(df, y1) * np.prod(liklihood(x_new, X1))
    
    p2= prior(df, y2) * np.prod(liklihood(x_new, X2))
    
    if p1>=p2:
        return 1
    
    elif p2>p1:
        return 0

In [23]:
make_d(df, y1, y2, x_new, X1, X2)

0